export const SYSTEM_USER = '/system/login'
export const MYSQL_QUERY = '/mysql/query'
export const MYSQL_PING = '/mysql/ping'
export const MYSQL_ADD = '/mysql/add'
export const MYSQL_LIST = '/mysql/list'
